openapi: 3.0.3
info:
  title: Library API
  version: 1.1.0
  description: STD22005
servers:
  - url: https://library.com
tags:
  - name: books
  - name: authors
  - name: books and authors relation
paths:
  /books:
    get:
      tags:
        - "books"
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - in: query
          name: startDate
          description: Start date of the release interval
          required: false
          schema:
            type: string
            format: datetime
        - in: query
          name: endDate
          description: End date of the release interval
          required: false
          schema:
            type: string
            format: datetime
        - in: query
          name: page
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          required: false
          schema:
            type: integer
            default: 50

      responses:
        200:
          description: The list of filtered books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    put:
      tags:
        - "books"
      summary: Create or update a list of books
      operationId: crupdateBooks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

  /authors:
    get:
      tags:
        - "authors"
      summary: get all authors
      operationId: getAuthors
      parameters:
        - in: query
          name: return authors by given name
          required: false
          schema:
            type: string
      responses:
        200:
          description: the list of filtered authors
          content:
            application/json:
              schema:
               type: array
               items:
                $ref: '#/components/schemas/Author'
    put:
      tags:
        - "authors"
      summary: Create or update a list of Author
      operationId: crupdateAuthor
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    delete:
      tags:
        - "authors"
      summary: delete an author
      operationId: deleteAuthor
      parameters:
        - in: query
          required: true
          name: author's name to delete
          schema:
            type: string
      responses:
        204:
          description: author deleted
  /authors/page/{page}/size/{size}:
    get:
      summary: retrieve authors with pagination
      tags:
        - "authors"
      parameters:
        - in: path
          name: page
          schema:
            type: integer
            default: 1
          required: true
        - in: path
          name: pageSize
          schema:
            type: integer
            default: 50
          required: true
      responses:
        200:
          description: OK

  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - "books and authors relation"
      summary: update author of a book
      operationId: updateBookIdAuthorId
      parameters:
        - name: bookId
          description: book's id to update
          in: path
          required: true
          schema:
            type: string
        - name: authorId
          description: new author's id
          in: path
          required: true
          schema:
            type: string
      responses:
         200:
          description: Author of the book updated successfully
         404:
          description: author or book's id not found
  /books/authors:
    put:
      tags:
        - "books and authors relation"
      summary: update book's author
      operationId: updateBookAuthor
      requestBody:
        content:
          application/json:
            schema : 
              type: array
              items:
                $ref: "#/components/schemas/UpdateBookAuthor"
      responses:
        200:
          description: Authors for books updated successfully
        404:
          description: authors or books not found
components:
  schemas:
    Book:
      allOf:
        - $ref: "#/components/schemas/crupdateBook"
      properties:
        author:
          $ref: "#/components/schemas/Author"
          
        
    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
    crupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: datetime

    UpdateBookAuthor:
      type: object
      properties:
        bookId: 
          type: string
        authorId:
          type: string

#2)
  #i-UpdateBookAuthor n'inclut que les identifiants car il est destiné à la mise à jour des relations entre les livres et les auteurs, sans 
  # modifier leurs autres propriétés individuelles.
#
  #ii- UpdateBookAuthor ne devrait inclure les propriétés de CrupdateBook et Author que si vous avez besoin de mettre à jour l'ensemble des 
  #  propriétés de ces entités en même temps que la mise à jour de leurs relations. La conception dépend des besoins spécifiques de votre application.
#
#4)
  # a- Oui,gérer la pagination à travers les entêtes de la requête est possible, mais peu courant. Les paramètres de pagination, tels que  
  # page page et pageSize, sont généralement inclus dans l'URL en tant que query parameters pour plus de clarté et de simplicité.

  # b- Non,il n'est pas nécessaire de gérer la pagination à travers les entêtes de la requête. L'utilisation de query parameters dans l'URL est 
  # la norme pour spécifier la pagination, car elle rend les paramètres de pagination plus accessibles et compréhensibles pour les utilisateurs de   # l'API